### ISSUE TITLE
resolve data dependancy and data consistency problems for dependant tables in a efficient way

### ISSUE THREAD

**Issue by 0xxlegolas** [projectawakening/world-chain-contracts#6]
Issue: 
- Currently there is no way to handle data dependency between related tables. Dependant data in multiple tables needs to manually updated. 

Suggestion 
- Explore [Store hooks](https://mud.dev/store/store-hooks) and implement data consistency in multiple tables and update all dependant tables.

**Comment by tinkrtailor** [comment]
Outdated, closing.
